### PR TITLE
find FOGs from one file per bout

### PR DESCRIPTION
**Pull request by AStefanko**
These two files read in from a directory and then run the FOG detection algorithm on them. findFOGs reads the files and then writes the results to a csv file, the other runs the FOG algorithm. This is basically the same as the original getFOGMarkers, but with different variable names, and it throws an error if the bout doesn't have enough data (usually when less than ten seconds).

### CODE REVIEW

**Review by VrutangShah — CHANGES_REQUESTED** [review]
Add example files..so if I download your code it should run without error. Also, add descriptions of the function files and what input files format required.
Change "limbs" to "Feet" as we specifically want to mention about the Feet algorithm.

**Comment by AStefanko** [comment]
> Change "limbs" to "Feet" as we specifically want to mention about the Feet algorithm.
Ok quick question on that. In the original algorithm, it can apply to feet or shanks, which is why I changed it to limbs. Is it ok if it's just feet? Will it confuse people who are using the shank measurements? Forgive me if I'm wrong on any of that

**Comment by AStefanko** [comment]
Ok @VrutangShah I have added example files and addressed your feedback! I did change it to feet, let me know if there is any better words. Let me know if I can send a zip to Martina.

**Comment by VrutangShah** [comment]
Yes please send a zip to me and Martina.
Thanks,
Vrutang

[OHSU email via VMware Boxer]

On May 3, 2020 7:03 PM, AStefanko <notifications@github.com> wrote:

Ok @VrutangShah<https://github.com/VrutangShah> I have added example files and addressed your feedback! I did change it to feet, let me know if there is any better words. Let me know if I can send a zip to Martina.

**Comment by VrutangShah** [comment]
We need different x,y,z axis depending upon the location of sensors (feet or shank). But I guess in our case we r just giving AP and ML so that should be okay. We can discuss this with Martina.

Further, I was also thinking the case where somebody wants to find FOG using both sensors (feet vs shank). In that case, we need two outputs.

Thanks,
Vrutang

[OHSU email via VMware Boxer]



On May 3, 2020 6:43 PM, AStefanko <notifications@github.com> wrote:

Change "limbs" to "Feet" as we specifically want to mention about the Feet algorithm.
Ok quick question on that. In the original algorithm, it can apply to feet or shanks, which is why I changed it to limbs. Is it ok if it's just feet? Will it confuse people who are using the shank measurements? Forgive me if I'm wrong on any of that

**Comment by VrutangShah** [comment]
This is a good question. Let discuss with Martina once she finish checking the code.

[OHSU email via VMware Boxer]

On May 3, 2020 7:27 PM, Vrutangkumar Shah <shahvr@ohsu.edu> wrote:
We need different x,y,z axis depending upon the location of sensors (feet or shank). But I guess in our case we r just giving AP and ML so that should be okay. We can discuss this with Martina.

Further, I was also thinking the case where somebody wants to find FOG using both sensors (feet vs shank). In that case, we need two outputs.

Thanks,
Vrutang

[OHSU email via VMware Boxer]



On May 3, 2020 6:43 PM, AStefanko <notifications@github.com> wrote:

Change "limbs" to "Feet" as we specifically want to mention about the Feet algorithm.
Ok quick question on that. In the original algorithm, it can apply to feet or shanks, which is why I changed it to limbs. Is it ok if it's just feet? Will it confuse people who are using the shank measurements? Forgive me if I'm wrong on any of that

**Review by VrutangShah — APPROVED** [review]

**Pull request merged**
